DROP TABLE IF EXISTS user;	
DROP TABLE IF EXISTS contacts;

CREATE TABLE user(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username VARCHAR(100) UNIQUE NOT NULL,
	email VARCHAR(60) UNIQUE NOT NULL,
	password VARCHAR(80) NOT NULL
);

CREATE TABLE contacts(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	name VARCHAR(60) NOT NULL,
	email VARCHAR(60) NOT NULL,
	phone VARCHAR(60) UNIQUE NOT NULL,
	
	FOREIGN KEY(user_id) REFERENCES user(id)

);
